### ISSUE TITLE
Swift 4 and Xcode 9.2 : error convert Data.SubSequence

### ISSUE THREAD

**Issue by hturkoz** [Dev1an/eID-Reader#7]
Hi
i have this error in Xcode 9.2 and Swift 4 : 
file : BEIDCard.swfit
line 99 : let ranges = loadDictionary(from: file.dropLast(2))

Error : Cannot convert value of type 'Data.SubSequence' (aka 'Data') to expected argument type 'MutableRangeReplaceableRandomAccessSlice<Data>' 

Regards

Edit : find fix by chance :) 

let ranges = loadDictionary(from: MutableRangeReplaceableRandomAccessSlice(file.dropLast(2)))

**Comment by Dev1an** [comment]
Hello Hanefi.
If you are upgrading the project to swift 4.x, you are more than welcome to submit your changes as a pull request.
